### ISSUE TITLE
Kebab & Snake with Upper/Lower/Title casing alternatives.

### ISSUE THREAD

**Issue by morilon** [Humanizr/Humanizer#1144]
I often use Kebab Case with Title Case to name my custom headers such as `X-My-Custom-Header`, I tried using the lib and I couldn't find the right combination, I might be doing something wrong, I don't know.

Basically what I wanted to know is;

`CanWeTurnThisValue` into

1. `This-Value-With-Title-Case`
2. `the-default-lower-case`
3. `OR-EVEN-ALL-UPPER`

**Comment by CpnNixel** [comment]
Hi @morilon .
Actually, there is something you can do for an X-given string.

1.  `string.Join("-", X.Humanize(LetterCasing.Title).Split(" "));`
2.  `x.Kebaberize();`
3. `string.Join("-", X.Humanize(LetterCasing.AllCaps).Split(" "));`

Cases 1 and 3 are not very friendly, and I suppose implementations can be added.

**Comment by gordon-matt** [comment]
The problem here could easily be solved more elegantly, if you were to address this related issue first:

https://github.com/Humanizr/Humanizer/issues/1149

Since Kebaberize just does this:

`return Underscore(input).Dasherize();`

and `Underscore()` automatically converts to lowercase, then that's why this is an issue for `Kebaberize()`.

Ideally, we should be able to do this:

`TheQuickBrownFox`

```text
.Kebaberize() -> The-Quick-Brown-Fox
.Kebaberize().ToLower() -> the-quick-brown-fox
.Kebaberize().ToUpper() -> THE-QUICK-BROWN-FOX
```

**Comment by morilon** [comment]
I ended up using my own implementation with a bit of regex precisely for the reason Gordon said; I needed the control the casing.

Thanks anyway, guys.
