### ISSUE TITLE
`DateOnly` from DateTime.MinValue returns "2 months ago"

### ISSUE THREAD

**Issue by 21r8390** [Humanizr/Humanizer#1189]
When I use `DateOnly` and want to put this into a readable form with Humanizer, I get the error that _"2 months ago"_ comes out for `DateTime.MinValue`. If I use DateTime, then I get the expected result of _"2022 years ago"_.

Examples:
```csharp
DateOnly.FromDateTime(DateTime.MinValue).Humanize(); // returns "2 months ago"
DateTime.MinValue.Humanize(); // returns "2022 years ago"
```

**Comment by 21r8390** [comment]
The workaround for this is to add:

```csharp
.ToDateTime(TimeOnly.MinValue).Humanize()
```

**Comment by hangy** [comment]
https://github.com/Humanizr/Humanizer/blob/937e827b8d664ce800b31160e51e8b2eca95fadc/src/Humanizer/DateTimeHumanizeStrategy/DateTimeHumanizeAlgorithms.cs#L158-L163

Does this need to use `DayNumber`  instead of  `DayOfYear`? I have a feeling that the current code doesn't work well with >1 year differences.

**Comment by hangy** [comment]
Probably related to #1186 or solved by it, if it gets a new implementation.

**Comment by Franetse7** [comment]
D'accord je vois tout les problème sur vos code source
Envoyer moi l'application

Le jeu. 15 févr. 2024, 10:37, Simon Cropp ***@***.***> a
écrit :
