### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by ptupitsyn** [Humanizr/Humanizer#1230]
No commits since March, PRs are ignored, can anyone please comment on this?

**Comment by 0xced** [comment]
I juste stumbled on #1219 (which is a duplicate of #1154) and saw that it's already fixed by #1178 in the main branch. Unfortunately a new package that includes this fix was never released on NuGet. 😟

@clairernovotny Is this project looking for a new maintainer? Any comment would be appreciated. 🙏

**Comment by JDA88** [comment]
I was about to start using the library, but I do not want to invest on an abandoned project, any status would be appreciated indeed :)

**Comment by Hefaistos68** [comment]
With the last changes made in January 2022 it seems there is not much going on lately.

**Comment by stefannikolei** [comment]
I started a fork of this project to keep it alive, cause there is no reaction from any maintainer since a year. 

What I changed is, the targetframeworks. I only target .net6. 

Also I had trouble publishing a package for each language  so there is only one package with all languages. 

The fork is over at https://github.com/Lingualizr/Lingualizr

**Comment by SimonCropp** [comment]
Project has been rebooted

**Comment by SimonCropp** [comment]
@0xced yes. hopefully doing a v3 beta1 in the next few days
