### ISSUE TITLE
Drop strong naming

### ISSUE THREAD

**Issue by MehdiK** [Humanizr/Humanizer#253]
I've been thinking about dropping strong naming from some of the OSS projects I've got. I've gone back and forth with the idea with urges to drop it and have then reconsidered to keep it because of the poor souls who HAVE to strong name their projects because some guy higher up the rank thinks it must be done. 

[Jeremy Miller's post](http://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/) did it for me. So I'm going to draw the line today. No more strong naming for vNexts of my OSS. If someone thinks this or other libraries are useful they will either have to use the older versions or drop their SN.

**Comment by onovotny** [comment]
While I agree wholeheartedly with dropping strong-naming, I will join the club of getting a crapload of pushback on my other projects where I tried that. Aside from being a breaking change, it does penalize people who don't have much, if any, control over it. Plus, there are some users (like VS Addins) that require strong naming.

The best compromise I've seen is the whole "OSS Signing" strategy, which just includes checking the key in. No lock-in (no security loss because there was never any).

**Comment by MehdiK** [comment]
I completely agree with you.

**Comment by onovotny** [comment]
I'll close this out then there's nothing further to do on this for v2.

**Comment by onovotny** [comment]
Re-opening this as @dsplaisted just released a tool to help people who do need strong named libraries use non-strong-named ones: https://github.com/dsplaisted/strongnamer

Is it acceptable to just tell the people that do need a strong name to install that `StrongNamer` package and have things "just work" for them?

**Comment by dsplaisted** [comment]
My advice would be to wait a while to see how well `StrongNamer` solves the issue.  I think it will work well but I hacked it together in two days for my presentation at .NET Unboxed, so it's still super new and untested. :-)

**Comment by hazzik** [comment]
Closing as it seems no one is interested in "fixing" this issue. my rationale is "do not break things": having Humanizer signed does not harm anyone (apart a few of anti-SN activists).
