### ISSUE TITLE
DateTime.Humanize, specify culture to use.

### ISSUE THREAD

**Issue by dmytro-gokun** [Humanizr/Humanizer#282]
It would be really cool if this method allowed to specify culture explicitly instead of taking current UI culture.

**Comment by canerelci** [comment]
Well guys, I'm glad you made this deal, because I am the one who needs more :)

I have a similar situation here and I need the Humanize() method to take specific CultureInfo because I even change them in loops. I am willing to the changes, because the other option for me is much harder. 

What do you think, should we extend Humanizer, or should I go create some wrappers etc? Of course, I also need performance.

**Comment by canerelci** [comment]
In short terms, I need to do: 

`stringVariable.Humanize(specificCulture)` 

I double checked the documentation and the source, but it seems string extension of Humanize does not take any arguments. DateTime and Timespan extensions have this optional parameter, as you discussed in this thread.

**Comment by MehdiK** [comment]
But how would `Humanize` use the provided culture? Can you provide a usage example with an input and expected output?

**Comment by canerelci** [comment]
This example is just one case I'm facing with:

I have a web service, which serves to many different cultures at the same time. This means I can't use Thread's CultureInfo but use request's culture to humanize/dehumanize etc. One example, generates some variables from Pascal cased strings, such as `WorkItem`. It will humanize `WorkItem` as `Work Item`, split words, and combine their first chars to generate `wi`. But the problem is, my thread culture should be tr-tr (Turkish-Turkey), and when I run this `Humanize(ToLower).Split().Select().Join()` sequence I get `wı` which is really lowercase I in Turkish language. This is a common error on almost all frameworks and international products, they fail on extended-latin alphabets like Turkish alphabet. So, my workaround was changing to `Humanize.Split.Join.ToLowerInvariant`. But I was not lucky for other similar situations, so I had to rewrite humanize-like methods to do similar transformations. 

If I had just an optional culture parameter to pass to Humanize, life would be easier for me :) The similar examples would become `str.Humanize(LetterCasing.Title, user.Culture).Split().Select().Join()` etc... 

Turkish has i and ı letters, and when you capitalize them, they will become İ and I, which creates the most of the confusion while transforming.

**Comment by MehdiK** [comment]
This is a very special case and I don't think it is something of a value to the broader community. So I might suggest you to create a wrapper extension method for your case.

If you could please share your wrapper method here, we could see how it's implemented and if it can be generalised to a useful addition for the library.

**Comment by Bartmax** [comment]
I'm importing data from an external source and want to Title case the data, we allow multiple culture/languages from the source so I also need to pass a culture to the Title casing. What would be a workaround?

**Comment by leus** [comment]
How do you guys recommend to user-test a multilingual application in the same computer?
