### ISSUE TITLE
Strange error with ToQuantity

### ISSUE THREAD

**Issue by olaj** [Humanizr/Humanizer#464]
Not sure if i should post this here or on for example Stack Overflow but i thought i try here first.

Two times now our sites has crashed with an error that Humanizer is throwing. It happens "randomly" and it seems like the site recover itself but i need some help to try to figure out what is happening and see if i can reproduce it somehow.

Error Message: Index was outside the bounds of the array.

at System.Collections.Generic.List`1.Contains(T item)
at Humanizer.Inflections.Vocabulary.ApplyRules(IList`1 rules, String word)
at Humanizer.Inflections.Vocabulary.Singularize(String word, Boolean inputIsKnownToBePlural)
at Humanizer.ToQuantityExtensions.ToQuantity(String input, Int32 quantity, ShowQuantityAs showQuantityAs, String format, IFormatProvider formatProvider)
at Humanizer.ToQuantityExtensions.ToQuantity(String input, Int32 quantity, ShowQuantityAs showQuantityAs)

So that is the error i get and i get it on the line

@("Category".ToQuantity(Model.Item.ListOfTagCategories.Count, ShowQuantityAs.None))

So my question is basically how can this error be? As i said it only happens randomly so it must be some kind of "outside variable" that is changing but i guess i need some help with from someone with good knowledge of the code to point me in the right direction.

I also think this might be some kind of bug since i guess Humanzier should handle this and just take a wild guess what to do?

Anyway, I'm happy with any help i can get.

**Comment by MaStr11** [comment]
This issue is most likely related to `List<T>` not being thread save as discussed here at [Stackoverflow](http://stackoverflow.com/a/36063121).
The exception is thrown in the [IsUncountable](https://github.com/Humanizr/Humanizer/blob/dev/src/Humanizer/Inflections/Vocabulary.cs#L132) method (The method is probably inlined in [ApplyRules](https://github.com/Humanizr/Humanizer/blob/dev/src/Humanizer/Inflections/Vocabulary.cs#L118) in release builds and is therefore not shown in the stack trace).

```CSharp
private readonly List<string> _uncountables = new List<string>();

private bool IsUncountable(string word)
{
    return _uncountables.Contains(word.ToLower()); // Exception is likley thrown here by the BCL.
}
```

These methods are writing to the `_uncountables` list:

* Vocabulary.cs [public void Vocabulary.AddUncountable(string word)](https://github.com/Humanizr/Humanizer/blob/dev/src/Humanizer/Inflections/Vocabulary.cs#L45)
* Vocabularies.cs [private static Vocabulary Vocabularies.BuildDefault()](https://github.com/Humanizr/Humanizer/blob/dev/src/Humanizer/Inflections/Vocabularies.cs#L25)

The second one is called by the initialization of `private static readonly Lazy<Vocabulary> Instance`. I don't see any problems there. I suspect that @olaj is adding custom words by calling `public void Vocabulary.AddUncountable` in a way that is not thread safe.

**Comment by ilanosortap** [comment]
Hey i am a beginner, can i work on this task?

**Comment by MehdiK** [comment]
Thanks @MaStr11 for investigating this.

@olaj any updates on this? Is still happening? Were you adding words in a non-safe manner?

**Comment by MehdiK** [comment]
Closing this now as there hasn't been any update on it for two years and I got no response to my previous enquiry. Happy to reopen if it's still happening.
