### ISSUE TITLE
Create better MVC (ASPNet 4.6) Sample

### ISSUE THREAD

**Issue by onovotny** [Humanizr/Humanizer#486]
The current sample has a lot of extra code beyond what's needed to show Humanizer as a `DataAnnotationsModelMetadataProvider`. 

It would be great to have a new slimmed-down sample that contains a minimal set of code/views to show demonstrate this.

**Comment by MehdiK** [comment]
Agreed. I've been thinking since the day I added the mvc sample to the repo
that whether that sample belonged to the repo! One idea I had was to create
a Humanizer.Mvc solution & package that would include some helpers for
using humanizer with mvc. Could include this provider plus things like
turning enums into select boxes etc.

Thoughts?

**Comment by gregfra** [comment]
Is this still a live issue? I'd like to claim it and provide a slimmed-down sample that works in the updated VS2017 and MVC framework. Humanizer helpers would be a separate issue and need some better specification, but I can handle the first issue,
