### ISSUE TITLE
Could not install tbb.redist

### ISSUE THREAD

**Issue by ghost** [Humanizr/Humanizer#565]
Could not install package 'tbb.redist 4.2.3.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by abdulateef** [comment]
thanks EgleValk, but i think since the framework is higher than the version of the package  it should accommodate it.So try the following process to be sure you have done the right thing
1. open visual studio
2. click on tools and then nugget management
3. click the console
4 after the pm> 
5. type "Install-Package tbb.redist"
then enter.
 if this process doesn't work then contact the package authors as suggested.
thank you

**Comment by SimonCropp** [comment]
closing due to no response
