### ISSUE TITLE
Update contributing guidelines with usage of +semver hints

### ISSUE THREAD

**Issue by hazzik** [Humanizr/Humanizer#570]
We are using the GitVersion, and it supports the automatic SemVer calculations. 
We need to update [CONTRIBUTING.md](https://github.com/Humanizr/Humanizer/blob/dev/CONTRIBUTING.md) and  [PULL_REQUEST_TEMPLATE.md](https://github.com/Humanizr/Humanizer/blob/dev/.github/PULL_REQUEST_TEMPLATE.md) to include the information on how to use this feature.

**Comment by SimonCropp** [comment]
@hazzik i propose we move off GitVersion. for context i am one of the original creators of GitVersion. and i no longer use it in any of my projects, nor recomend it to others. GitVersion predates the the simplified versioning of the new sdk style projects. ie now we can have a single version number that is applied to nugets, assembly versions and metadata. and when GitVersion fails, due to some git tree structure it doesnt understand, it is very difficult to debug.

**Comment by hazzik** [comment]
I’m ok with it, since we never started using the commit hints nor semantic commits.

**Comment by SimonCropp** [comment]
@hazzik 👍🏻
