### ISSUE TITLE
Transform(To.TitleCase) inconsistent transformations(?)

### ISSUE THREAD

**Issue by sushihangover** [Humanizr/Humanizer#584]
I am seeing inconsistent transformations when using `To.TitleCase` with all capital strings, but if I transform them to lower case and than use title casing the results are correct:

```
"SUICIDE SQUAD".Transform(To.TitleCase)
"SUICIDE SQUAD".Transform(To.LowerCase).Transform(To.TitleCase)
```

No Change:

> SUICIDE SQUAD
> Suicide Squad

```
"PETE'S DRAGON".Transform(To.TitleCase)
"PETE'S DRAGON".Transform(To.LowerCase).Transform(To.TitleCase)
```

Transform stops after first hyphenated word:

> Pete's DRAGON
> Pete's Dragon

```
"CAPTAIN AMERICA: CIVIL WAR".Transform(To.TitleCase)
"CAPTAIN AMERICA: CIVIL WAR".Transform(To.LowerCase).Transform(To.TitleCase)
```

Only second word is transformed:

> CAPTAIN America: CIVIL WAR
> Captain America: Civil War

Version:

> package id="Humanizer" version="2.1.0" targetFramework="net45"

**Comment by hazzik** [comment]
Works [almost] as designed. All caps words treated as abbreviations and
skipped. IMO only incorrect behavior is last one, where it treats colons as
a part of the word.

**Comment by sushihangover** [comment]
Thanks for the info, need to RTFC ;-) 

I'm using Humanizer for mainly "computerized" strings (_amazing collection of extensions_!) but since I already had it available in this project, figured I use for some 'normal' strings transformations...

I'll roll my own title casing for this case to avoid the extra string mutations.

**Comment by aloisdg** [comment]
> All caps words treated as abbreviations and skipped.

I think CSS `text-transform:capitalize;` includes something like this too.

**Comment by Ashera138** [comment]
I checked out those examples since the `ToTitleCase()` method changed [in this PR](https://github.com/Humanizr/Humanizer/pull/741).

Input | Output
------------ | -------------
`"SUICIDE SQUAD".Transform(To.TitleCase)` | SUICIDE SQUAD
`"SUICIDE SQUAD".Transform(To.LowerCase).Transform(To.TitleCase)` | Suicide Squad
`"PETE'S DRAGON".Transform(To.TitleCase)` | PETE'S DRAGON
`"PETE'S DRAGON".Transform(To.LowerCase).Transform(To.TitleCase)` | Pete'S Dragon
`"CAPTAIN AMERICA: CIVIL WAR".Transform(To.TitleCase)` | CAPTAIN AMERICA: CIVIL WAR
`"CAPTAIN AMERICA: CIVIL WAR".Transform(To.LowerCase).Transform(To.TitleCase)` | Captain America: Civil War

As mentioned above, 
>All caps words are treated as abbreviations and skipped.

which means the only one of these that returns an incorrect result now is the second one (Pete's Dragon). The "s" after the apostrophe should not be capitalized.

I'll take a look at the `ToTitleCase()` method and make some changes to cover this. 👍
