### ISSUE TITLE
Croatian localization of TimeSpan fails with >1 day

### ISSUE THREAD

**Issue by lzybkr** [Humanizr/Humanizer#597]
My repro is using PowerShell, but there is a null reference exception when the number of days is > 1 and the culture is `hr`.

```
#32 PS> [Humanizer.TimeSpanHumanizeExtensions]::Humanize([timespan]::new(1,1,1,1,1), 5, [CultureInfo]'hr')
1 dan, 1 sat, 1 minuta, 1 sekunda, 1 milisekunda

#33 PS> [Humanizer.TimeSpanHumanizeExtensions]::Humanize([timespan]::new(2,1,1,1,1), 5, [CultureInfo]'hr')
Exception calling "Humanize" with "3" argument(s): "Value cannot be null.
Parameter name: format"
At line:1 char:1
+ [Humanizer.TimeSpanHumanizeExtensions]::Humanize([timespan]::new(2,1, ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException
 ```

**Comment by hangy** [comment]
Interesting. There seem to be some special resources for different plurals in the Croatian language (see https://github.com/Humanizr/Humanizer/blob/a204909f36c18bfed2d9b399a5b2f55e9fe41dda/src/Humanizer/Localisation/Formatters/CroatianFormatter.cs#L5). There is no `TimeSpanHumanize_MultipleDays` resource in https://github.com/Humanizr/Humanizer/blob/a204909f36c18bfed2d9b399a5b2f55e9fe41dda/src/Humanizer/Properties/Resources.hr.resx though, so that the resolved format is `null` and thus the call to `string.Format` fails.
I suppose it should work for timespans of ie. 15 days ..? Do you know if these different plural forms are even required for days?

**Comment by lzybkr** [comment]
I don't know Croatian. I found this experimenting with all possible languages to help produce this comment: https://github.com/PowerShell/PowerShell/pull/2689#issuecomment-262035441
