### ISSUE TITLE
Do not pluralize when non-English culture is active (Thread.CurrentThread.CurrentUICulture)

### ISSUE THREAD

**Issue by vitamink** [Humanizr/Humanizer#668]
I am pluralizing words from a resource file. So, for example, the word "site" is pluralized to "sites", which is good. But when the current culture is Japanese, the word "サイト" is pluralized to "サイトs", which is incorrect. I'd expect Humanizer to leave the word as サイト, and the addition of the "s" is totally incorrect.

**Comment by hazzik** [comment]
@vitamink currently Pluralize/Singularize is only supported for English. You would need to check the language yourself before trying the transformation.

**Comment by vitamink** [comment]
Okay, I understand this, so why not simply return the same string when not in an English culture, and pluralize when in English. It current implementation makes it hard to support multiple languages.

I could wrap the pluralize method in another method, or create a fork that does this, but it really seems like a relatively simple solution to just NOT pluralize when the language is not English...

**Comment by vitamink** [comment]
Simplest solution... wrapper extension method.

    public static string PluralizeEnglish(this string word, bool inputIsKnownToBeSingular = true)
    {
        if (string.Equals(Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName, "en",
            StringComparison.OrdinalIgnoreCase))
        {
            return word.Pluralize();
        }
        return word;
    }

Thanks :-)

**Comment by MehdiK** [comment]
Not to say the current behavior of the library is correct; but IMO that check doesn't belong to Humanizer - it belongs to the caller. I'd say the correct behavior of the library is to bork out with an unsupported functionality kinda exception when it's asked to do something it doesn't support instead of defaulting to a certain language, returning the input or any other solution. Returning the input might be the right solution for most Japanese words; but I am quite certain that's not the case for all languages.

In absence of proper support for other languages or a common acceptable return for unsupported languages, your wrapping extension is the way forward.
