### ISSUE TITLE
[Feature Request] "int" extension method for humanizing to tuple strings

### ISSUE THREAD

**Issue by Kermalis** [Humanizr/Humanizer#709]
Similar to int.Ordinalize(), a method that returns:

    1.Tupleize() - "single"
    2.Tupleize() - "pair"
    3.Tupleize() - "triple"
    4.Tupleize() - "quadruple"
    5.Tupleize() - "quintuple"
    ...
    100.Tupleize() - "centuple"
    1000.Tupleize() - "milluple"

My use case is very simple. My Sudoku solver prints out "Naked Pair", "Hidden triple" and the like. I have the tuple strings in a little array: `string[] tupleStr = new string[] { "", "single", "pair", "triple", "quadruple" };`
However, I can see other people finding more important uses for this, especially in multiple languages.

**Comment by mannixc** [comment]
Hi - I've made a small change to implement this feature - see #743. I've limited the scope so far to just the numbers 1-10, 100 and 1000, as beyond that it gets a bit convoluted and rarely used. 

Any other number n will return "n-tuple" instead. I've also used "double" instead of "pair" as it seems more appropriate.

Please let me know what you think, I wasn't sure whether I should do anything in the way of localization?
