### ISSUE TITLE
nuget packaging is not very managable

### ISSUE THREAD

**Issue by medvjed** [Humanizr/Humanizer#887]
I really like this project, however, the nuget packaging...
a package for every language which is 40. Imagine if you supported even more languages next year
Imagine if every other package in my project (80+) would have 50 packages for every language.
I would have 4000 packages to scroll through.

It should be just one.
If a language updates you should update the whole package.
to 2.7.10

**Comment by onovotny** [comment]
This is by design as many people expressed an interest/need in being able to only have specific languages in their application. 

Using satellite packages is the only option NuGet provides for this.

Are you using packages.config or PackageReference for your NuGet packages? The easiest way to get them all is to add `Humanizer` and the rest are transitively brought in.
